// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exercises.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countExercises = `-- name: CountExercises :one
SELECT COUNT(*) FROM exercises e
WHERE
  ($1::text    IS NULL OR EXISTS (
     SELECT 1 FROM exercise_muscles em
     WHERE em.exercise_id = e.id AND em.muscle = $1::text))
  AND ($2::text IS NULL OR e.equipment = $2::text)
  AND ($3::text     IS NULL OR e.level     = $3::text)
  AND ($4::text         IS NULL OR e.name ILIKE '%' || $4::text || '%')
`

type CountExercisesParams struct {
	Muscle    pgtype.Text `json:"muscle"`
	Equipment pgtype.Text `json:"equipment"`
	Level     pgtype.Text `json:"level"`
	Q         pgtype.Text `json:"q"`
}

func (q *Queries) CountExercises(ctx context.Context, arg CountExercisesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countExercises,
		arg.Muscle,
		arg.Equipment,
		arg.Level,
		arg.Q,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMusclesForExercise = `-- name: DeleteMusclesForExercise :exec
DELETE FROM exercise_muscles WHERE exercise_id = $1
`

func (q *Queries) DeleteMusclesForExercise(ctx context.Context, exerciseID string) error {
	_, err := q.db.Exec(ctx, deleteMusclesForExercise, exerciseID)
	return err
}

const exerciseExists = `-- name: ExerciseExists :one
SELECT EXISTS(SELECT 1 FROM exercises WHERE id = $1)
`

func (q *Queries) ExerciseExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, exerciseExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const exerciseExistsByIDs = `-- name: ExerciseExistsByIDs :many
SELECT id FROM exercises WHERE id = ANY($1::text[])
`

func (q *Queries) ExerciseExistsByIDs(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, exerciseExistsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExerciseByID = `-- name: GetExerciseByID :one
SELECT id, name, force, level, mechanic, equipment,
       category, instructions, image_urls,
       created_at, updated_at
FROM exercises
WHERE id = $1
`

func (q *Queries) GetExerciseByID(ctx context.Context, id string) (Exercise, error) {
	row := q.db.QueryRow(ctx, getExerciseByID, id)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Force,
		&i.Level,
		&i.Mechanic,
		&i.Equipment,
		&i.Category,
		&i.Instructions,
		&i.ImageUrls,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMusclesForExercise = `-- name: GetMusclesForExercise :many
SELECT muscle, role
FROM exercise_muscles
WHERE exercise_id = $1
ORDER BY role, muscle
`

type GetMusclesForExerciseRow struct {
	Muscle string `json:"muscle"`
	Role   string `json:"role"`
}

func (q *Queries) GetMusclesForExercise(ctx context.Context, exerciseID string) ([]GetMusclesForExerciseRow, error) {
	rows, err := q.db.Query(ctx, getMusclesForExercise, exerciseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMusclesForExerciseRow{}
	for rows.Next() {
		var i GetMusclesForExerciseRow
		if err := rows.Scan(&i.Muscle, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMusclesForExercises = `-- name: GetMusclesForExercises :many
SELECT exercise_id, muscle, role
FROM exercise_muscles
WHERE exercise_id = ANY($1::text[])
ORDER BY exercise_id, role, muscle
`

func (q *Queries) GetMusclesForExercises(ctx context.Context, dollar_1 []string) ([]ExerciseMuscle, error) {
	rows, err := q.db.Query(ctx, getMusclesForExercises, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExerciseMuscle{}
	for rows.Next() {
		var i ExerciseMuscle
		if err := rows.Scan(&i.ExerciseID, &i.Muscle, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMuscle = `-- name: InsertMuscle :exec
INSERT INTO exercise_muscles (exercise_id, muscle, role)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type InsertMuscleParams struct {
	ExerciseID string `json:"exercise_id"`
	Muscle     string `json:"muscle"`
	Role       string `json:"role"`
}

func (q *Queries) InsertMuscle(ctx context.Context, arg InsertMuscleParams) error {
	_, err := q.db.Exec(ctx, insertMuscle, arg.ExerciseID, arg.Muscle, arg.Role)
	return err
}

const listExercises = `-- name: ListExercises :many
SELECT e.id, e.name, e.force, e.level, e.mechanic, e.equipment,
       e.category, e.instructions, e.image_urls,
       e.created_at, e.updated_at
FROM exercises e
WHERE
  ($1::text    IS NULL OR EXISTS (
     SELECT 1 FROM exercise_muscles em
     WHERE em.exercise_id = e.id AND em.muscle = $1::text))
  AND ($2::text IS NULL OR e.equipment = $2::text)
  AND ($3::text     IS NULL OR e.level     = $3::text)
  AND ($4::text         IS NULL OR e.name ILIKE '%' || $4::text || '%')
ORDER BY e.name
LIMIT  $6
OFFSET $5
`

type ListExercisesParams struct {
	Muscle    pgtype.Text `json:"muscle"`
	Equipment pgtype.Text `json:"equipment"`
	Level     pgtype.Text `json:"level"`
	Q         pgtype.Text `json:"q"`
	Off       int32       `json:"off"`
	Lim       int32       `json:"lim"`
}

func (q *Queries) ListExercises(ctx context.Context, arg ListExercisesParams) ([]Exercise, error) {
	rows, err := q.db.Query(ctx, listExercises,
		arg.Muscle,
		arg.Equipment,
		arg.Level,
		arg.Q,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Exercise{}
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Force,
			&i.Level,
			&i.Mechanic,
			&i.Equipment,
			&i.Category,
			&i.Instructions,
			&i.ImageUrls,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExercise = `-- name: UpsertExercise :exec
INSERT INTO exercises (id, name, force, level, mechanic, equipment, category, instructions, image_urls)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO UPDATE SET
  name         = EXCLUDED.name,
  force        = EXCLUDED.force,
  level        = EXCLUDED.level,
  mechanic     = EXCLUDED.mechanic,
  equipment    = EXCLUDED.equipment,
  category     = EXCLUDED.category,
  instructions = EXCLUDED.instructions,
  image_urls   = EXCLUDED.image_urls,
  updated_at   = now()
`

type UpsertExerciseParams struct {
	ID           string      `json:"id"`
	Name         string      `json:"name"`
	Force        pgtype.Text `json:"force"`
	Level        string      `json:"level"`
	Mechanic     pgtype.Text `json:"mechanic"`
	Equipment    pgtype.Text `json:"equipment"`
	Category     string      `json:"category"`
	Instructions []string    `json:"instructions"`
	ImageUrls    []string    `json:"image_urls"`
}

func (q *Queries) UpsertExercise(ctx context.Context, arg UpsertExerciseParams) error {
	_, err := q.db.Exec(ctx, upsertExercise,
		arg.ID,
		arg.Name,
		arg.Force,
		arg.Level,
		arg.Mechanic,
		arg.Equipment,
		arg.Category,
		arg.Instructions,
		arg.ImageUrls,
	)
	return err
}
