// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Exercise struct {
	ID           string             `json:"id"`
	Name         string             `json:"name"`
	Force        pgtype.Text        `json:"force"`
	Level        string             `json:"level"`
	Mechanic     pgtype.Text        `json:"mechanic"`
	Equipment    pgtype.Text        `json:"equipment"`
	Category     string             `json:"category"`
	Instructions []string           `json:"instructions"`
	ImageUrls    []string           `json:"image_urls"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ExerciseMuscle struct {
	ExerciseID string `json:"exercise_id"`
	Muscle     string `json:"muscle"`
	Role       string `json:"role"`
}

type ExerciseVariant struct {
	ID          int64              `json:"id"`
	ExerciseID  string             `json:"exercise_id"`
	VariantName string             `json:"variant_name"`
	Description pgtype.Text        `json:"description"`
	Source      string             `json:"source"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
