// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountExercises(ctx context.Context, arg CountExercisesParams) (int64, error)
	DeleteMusclesForExercise(ctx context.Context, exerciseID string) error
	ExerciseExists(ctx context.Context, id string) (bool, error)
	ExerciseExistsByIDs(ctx context.Context, dollar_1 []string) ([]string, error)
	GetExerciseByID(ctx context.Context, id string) (Exercise, error)
	GetMusclesForExercise(ctx context.Context, exerciseID string) ([]GetMusclesForExerciseRow, error)
	GetMusclesForExercises(ctx context.Context, dollar_1 []string) ([]ExerciseMuscle, error)
	InsertMuscle(ctx context.Context, arg InsertMuscleParams) error
	ListCategories(ctx context.Context) ([]string, error)
	ListEquipment(ctx context.Context) ([]pgtype.Text, error)
	ListExercises(ctx context.Context, arg ListExercisesParams) ([]Exercise, error)
	ListLevels(ctx context.Context) ([]string, error)
	ListMuscles(ctx context.Context) ([]string, error)
	UpsertExercise(ctx context.Context, arg UpsertExerciseParams) error
}

var _ Querier = (*Queries)(nil)
