// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: taxonomy.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listCategories = `-- name: ListCategories :many
SELECT DISTINCT category FROM exercises ORDER BY category
`

func (q *Queries) ListCategories(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var category string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEquipment = `-- name: ListEquipment :many
SELECT DISTINCT equipment FROM exercises WHERE equipment IS NOT NULL ORDER BY equipment
`

func (q *Queries) ListEquipment(ctx context.Context) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, listEquipment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var equipment pgtype.Text
		if err := rows.Scan(&equipment); err != nil {
			return nil, err
		}
		items = append(items, equipment)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLevels = `-- name: ListLevels :many
SELECT DISTINCT level FROM exercises ORDER BY level
`

func (q *Queries) ListLevels(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listLevels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var level string
		if err := rows.Scan(&level); err != nil {
			return nil, err
		}
		items = append(items, level)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMuscles = `-- name: ListMuscles :many
SELECT DISTINCT muscle FROM exercise_muscles ORDER BY muscle
`

func (q *Queries) ListMuscles(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listMuscles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var muscle string
		if err := rows.Scan(&muscle); err != nil {
			return nil, err
		}
		items = append(items, muscle)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
