// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: variants.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countExerciseVariants = `-- name: CountExerciseVariants :one
SELECT COUNT(*) FROM exercise_variants
`

func (q *Queries) CountExerciseVariants(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countExerciseVariants)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listVariantsForExercise = `-- name: ListVariantsForExercise :many
SELECT id, exercise_id, variant_name, description, source, created_at
FROM exercise_variants
WHERE exercise_id = $1
ORDER BY variant_name
`

func (q *Queries) ListVariantsForExercise(ctx context.Context, exerciseID string) ([]ExerciseVariant, error) {
	rows, err := q.db.Query(ctx, listVariantsForExercise, exerciseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExerciseVariant{}
	for rows.Next() {
		var i ExerciseVariant
		if err := rows.Scan(
			&i.ID,
			&i.ExerciseID,
			&i.VariantName,
			&i.Description,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchExerciseByFuzzyName = `-- name: SearchExerciseByFuzzyName :many
SELECT id, name, similarity(name, $1::text) AS sim
FROM exercises
WHERE name % $1::text
ORDER BY sim DESC, name
LIMIT $2
`

type SearchExerciseByFuzzyNameParams struct {
	Q   string `json:"q"`
	Lim int32  `json:"lim"`
}

type SearchExerciseByFuzzyNameRow struct {
	ID   string  `json:"id"`
	Name string  `json:"name"`
	Sim  float32 `json:"sim"`
}

// Trigram similarity against the catalog. Returns top N matches above the operator threshold.
func (q *Queries) SearchExerciseByFuzzyName(ctx context.Context, arg SearchExerciseByFuzzyNameParams) ([]SearchExerciseByFuzzyNameRow, error) {
	rows, err := q.db.Query(ctx, searchExerciseByFuzzyName, arg.Q, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchExerciseByFuzzyNameRow{}
	for rows.Next() {
		var i SearchExerciseByFuzzyNameRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Sim); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExerciseVariant = `-- name: UpsertExerciseVariant :one
INSERT INTO exercise_variants (exercise_id, variant_name, description, source)
VALUES ($1, $2, $3, $4)
ON CONFLICT (exercise_id, variant_name) DO UPDATE
  SET description = EXCLUDED.description,
      source      = EXCLUDED.source
RETURNING (xmax = 0) AS inserted
`

type UpsertExerciseVariantParams struct {
	ExerciseID  string      `json:"exercise_id"`
	VariantName string      `json:"variant_name"`
	Description pgtype.Text `json:"description"`
	Source      string      `json:"source"`
}

// Returns true when a new row was inserted, false when an existing variant was updated.
func (q *Queries) UpsertExerciseVariant(ctx context.Context, arg UpsertExerciseVariantParams) (bool, error) {
	row := q.db.QueryRow(ctx, upsertExerciseVariant,
		arg.ExerciseID,
		arg.VariantName,
		arg.Description,
		arg.Source,
	)
	var inserted bool
	err := row.Scan(&inserted)
	return inserted, err
}
